export const FETCH_PRODUCT_REQUAST = 'FETCH_PRODUCT_REQUAST';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILUAR = 'FETCH_PRODUCT_FAILUAR';
export const ADD_ITEM = 'ADD_ITEM';
export const DEL_ITEM = 'DEL_ITEM';
export const ADJUST_QTY = 'ADJUST_QTY';
export const ADD_FAVORITE = 'ADD_FAVORITE';
export const DEL_FAVORITE = 'DEL_FAVORITE';